IMAGE_NAME = "bento/ubuntu-24.04"

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false

    config.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.cpus = 1
    end

    config.vm.define "ubuntu" do |ubuntu|
        ubuntu.vm.box = IMAGE_NAME
        ubuntu.vm.network "forwarded_port", guest: 22, host: 2207, host_ip: "127.0.0.1"
	ubuntu.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
        ubuntu.vm.hostname = "ubuntu"
    end

    config.vm.provision "file", source: "LVPublic.pub", destination: "/home/vagrant/.ssh/me.pub"
    config.vm.provision "shell", inline: <<-SHELL
    cat /home/vagrant/.ssh/me.pub >> /home/vagrant/.ssh/authorized_keys

    SHELL

    config.vm.provision "shell", inline: <<-SHELL
  	sudo apt update
  	sudo apt install -y apache2
  	sudo systemctl enable apache2
  	sudo systemctl start apache2
    SHELL

end
